"""Utility helpers: config loading, DDP setup, box-drawing logging."""

from coe_ctc.utils.config import load_yaml, merge_overrides, resolve_paths
from coe_ctc.utils.distributed import (
    barrier,
    get_local_rank,
    get_rank,
    get_world_size,
    is_distributed,
    is_main_process,
    setup_distributed,
    teardown_distributed,
    unwrap_model,
)
from coe_ctc.utils.logging import (
    BOX_W,
    box_bottom,
    box_inner_bottom,
    box_inner_top,
    box_line,
    box_section_title,
    box_top,
    bytes_to_human,
    format_duration,
    make_progress_bar,
    make_sparkline,
    setup_logger,
)

__all__ = [
    "BOX_W",
    "barrier",
    "box_bottom",
    "box_inner_bottom",
    "box_inner_top",
    "box_line",
    "box_section_title",
    "box_top",
    "bytes_to_human",
    "format_duration",
    "get_local_rank",
    "get_rank",
    "get_world_size",
    "is_distributed",
    "is_main_process",
    "load_yaml",
    "make_progress_bar",
    "make_sparkline",
    "merge_overrides",
    "resolve_paths",
    "setup_distributed",
    "setup_logger",
    "teardown_distributed",
    "unwrap_model",
]
